services:
  satpass-db:
      image: postgres:16-alpine
      container_name: satpass-db
      environment:
        POSTGRES_DB: satpass
        POSTGRES_USER: satpass_user
        POSTGRES_PASSWORD: satpass_password
      volumes:
        - satpass_db_data:/var/lib/postgresql/data
        - ../satellite_pass/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

      ports:
      - "5435:5432"   # host:container
     
  satpass-api:
    build:
      context: ../satellite_pass
      dockerfile: Dockerfile
    container_name: satpass-api
    environment:
      FLASK_ENV: production
      SATPASS_DB_HOST: satpass-db
      SATPASS_DB_PORT: 5432
      SATPASS_DB_NAME: satpass
      SATPASS_DB_USER: satpass_user
      SATPASS_DB_PASSWORD: satpass_password
      JWT_SECRET: "JQMsFWoyn4xd3UdAlNt2QFBbSbRyu6qiSAIyXnZZ/NOlqYa1uJ3Q1ZbY3b/4veos"
    depends_on:
      - satpass-db
    ports:
      - "8085:8000"   # host:container
   
  db:
    image: postgres:16-alpine
    container_name: satellite_tickets_db 
    environment:
      POSTGRES_DB: satellite_tickets 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  backup:
    image: postgres:16-alpine
    container_name: satellite_tickets_backup
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: satellite_tickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Istanbul  # Set your timezone
    volumes:
      - ../db/backups:/backups  # Backups stored on host
      - ../db/backup-scripts:/scripts  # Backup scripts
    entrypoint: /scripts/backup-entrypoint.sh
  

volumes:
  redis-data:
  postgres_data:
  satpass_db_data:
