services:
  satellite-pass:
    build:
      context: ../satellite_pass
      dockerfile: Dockerfile
    container_name: satellite-pass
    environment:
      - TLE_URL=https://celestrak.org/NORAD/elements/gp.php?CATNR=41875&FORMAT=TLE
      - NORAD_ID=41875
      - TLE_UPDATE_HOUR=3
    ports:
      - "5001:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  

  db:
    image: postgres:16-alpine
    container_name: satellite_tickets_db 
    environment:
      POSTGRES_DB: satellite_tickets 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  backup:
    image: postgres:16-alpine
    container_name: satellite_tickets_backup
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: satellite_tickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Istanbul  # Set your timezone
    volumes:
      - ../db/backups:/backups  # Backups stored on host
      - ../db/backup-scripts:/scripts  # Backup scripts
    entrypoint: /scripts/backup-entrypoint.sh
  

volumes:
  redis-data:
  postgres_data:
  skyfield_data:
  tle_data:
